spring.application.name=RouteSense

# Connect to the Docker Database we just created
spring.datasource.url=jdbc:postgresql://localhost:5432/routesense_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Auto-create tables (Magic setting for prototypes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect