spring.application.name=RouteSense

## Connect to the Docker Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/routesense_db
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Auto-create tables
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Cloud Database Configuration
spring.datasource.url=jdbc:postgresql://ep-old-morning-a1nvg63z.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# Create tables automatically
spring.jpa.hibernate.ddl-auto=update

# Security Configuration
routesense.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# routesense.app.jwtExpirationMs=86400000 // 24 HRS
routesense.app.jwtExpirationMs=86400000

# Map box API key
mapbox.access.token=${MAPBOX_TOKEN}

# values
routesense.app.fuel.diesel-price=277.0

# ml model
routesense.ml.base-url=${ML_URL}


# Email Configuration
resend.api-key=${RESEND_API_KEY}